service: slack-my-amazon
provider:
  name: aws
  runtime: nodejs8.10
plugins:
  - serverless-mocha-plugin
functions:
  hello:
    handler: handler.hello
#    events:
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
