service: cloud-slacker
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10
plugins:
  - serverless-mocha-plugin
functions:
  code-build:
    handler: handlers/code-build.notify
    environment:
      slack_url: ${opt:slack_url}
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.codebuild"
            detail-type:
              - "CodeBuild Build State Change"
            detail:
              build-status:
                - 'IN_PROGRESS'
                - 'SUCCEEDED'
                - 'FAILED'
                - 'STOPPED'
