service: slack-my-amazon
provider:
  name: aws
  runtime: nodejs8.10
plugins:
  - serverless-mocha-plugin
functions:
  hello:
    handler: handler.hello
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.codebuild"
            detail-type:
              - "CodeBuild Build State Change"
            detail:
              build-status:
                - 'IN_PROGRESS'
                - 'SUCCEEDED'
                - 'FAILED'
                - 'STOPPED'
